<?php
// $Id: xoops_version.php,v 1.1 17/03/2005 12:01:00 AdminOne Exp $
//  ------------------------------------------------------------------------ //
//            RM+SOFT - Sistema de Galería Fotográfica en Línea              //
//                Copyright Red México Soft © 2005. (Eduardo Cortés)         //
//                     <http://www.redmexico.com.mx/>                        //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//  ------------------------------------------------------------------------ //
//	Este programa es un programa libre; puedes distribuirlo y modificarlo	 //
//	bajo los términos de al GNU General Public Licencse como ha sido		 //
//	publicada por The Free Software Foundation (Fundación de Software Libre; //
//	en cualquier versión 2 de la Licencia o mas reciente.					 //
//                                                                           //
//	Este programa es distribuido esperando que sea últil pero SIN NINGUNA	 //
//	GARANTÍA. Ver The GNU General Public License para mas detalles.			 //
//  ------------------------------------------------------------------------ //
//	Questions, Bugs or any comment plese write me						 	 //
//	Preguntas, errores o cualquier comentario escribeme						 //
//	<adminone@redmexico.com.mx>												 //
//  ------------------------------------------------------------------------ //

$modversion['name'] = "RM+Soft GS";
$modversion['version'] = 1.1;
$modversion['description'] = _MI_RMGAL_DESC;
$modversion['author'] = "Eduardo Cortés (AdminOne) http://www.redmexico.com.mx";
$modversion['credits'] = "AdminOne";
$modversion['help'] = "";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/logo.png";
$modversion['dirname'] = "rmgallery";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "rmgal_gals";
$modversion['tables'][1] = "rmgal_pics";
$modversion['tables'][2] = "rmgal_postal";
$modversion['tables'][3] = "rmgal_sizes";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

$modversion['hasMain'] = 1;

// Blocks
$modversion['blocks'][1]['file'] = "rmgal_recent_cats.php";
$modversion['blocks'][1]['name'] = _MI_RMGAL_BNAME1;
$modversion['blocks'][1]['description'] = _MI_RMGAL_BDESC1;
$modversion['blocks'][1]['show_func'] = "bshow_recent_cats";
$modversion['blocks'][1]['template'] = 'rmgal_block_recentcats.html';

$modversion['blocks'][2]['file'] = "rmgal_recent_pics.php";
$modversion['blocks'][2]['name'] = _MI_RMGAL_BNAME2;
$modversion['blocks'][2]['description'] = _MI_RMGAL_BDESC2;
$modversion['blocks'][2]['show_func'] = "bshow_recent_pics";
$modversion['blocks'][2]['template'] = 'rmgal_block_recentpics.html';

$modversion['blocks'][3]['file'] = "rmgal_random_pics.php";
$modversion['blocks'][3]['name'] = _MI_RMGAL_BNAME3;
$modversion['blocks'][3]['description'] = _MI_RMGAL_BDESC3;
$modversion['blocks'][3]['show_func'] = "bshow_random_pics";
$modversion['blocks'][3]['template'] = 'rmgal_block_random.html';

$modversion['blocks'][4]['file'] = "rmgal_last_catego.php";
$modversion['blocks'][4]['name'] = _MI_RMGAL_BNAME4;
$modversion['blocks'][4]['description'] = _MI_RMGAL_BDESC4;
$modversion['blocks'][4]['show_func'] = "bshow_last_catego";
$modversion['blocks'][4]['edit_func'] = "bedit_last_items";
$modversion['blocks'][4]['options'] = "1|d/m/Y";
$modversion['blocks'][4]['template'] = 'rmgal_last_catego.html';

// Search
//$modversion['hasSearch'] = 1;
//$modversion['search']['file'] = "include/search.inc.php";
//$modversion['search']['func'] = "rmlib_search";

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'idimg';
$modversion['comments']['pageName'] = 'images.php';
$modversion['comments']['extraParams'] = '';

// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comments.php';
$modversion['comments']['callback']['approve'] = 'rmgal_com_approve';
$modversion['comments']['callback']['update'] = 'rmgal_com_update';

// Templates
$modversion['templates'][1]['file'] = 'rmgal_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'rmgal_navbar.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'rmgal_categos.html';
$modversion['templates'][3]['description'] = '';
$modversion['templates'][4]['file'] = 'rmgal_categos_detail.html';
$modversion['templates'][4]['description'] = '';
$modversion['templates'][5]['file'] = 'rmgal_nav_top.html';
$modversion['templates'][5]['description'] = '';
$modversion['templates'][6]['file'] = 'rmgal_image_detail.html';
$modversion['templates'][6]['description'] = '';
$modversion['templates'][7]['file'] = 'rmgal_postcard_new.html';
$modversion['templates'][7]['description'] = '';
$modversion['templates'][8]['file'] = 'rmgal_bgcolor.html';
$modversion['templates'][8]['description'] = 'Archivo para colores de fondo de las postales';
$modversion['templates'][9]['file'] = 'rmgal_border_color.html';
$modversion['templates'][9]['description'] = 'Archivo para colores de borde de las postales';
$modversion['templates'][10]['file'] = 'rmgal_font_color.html';
$modversion['templates'][10]['description'] = 'Archivo de color para el texto';
$modversion['templates'][11]['file'] = 'rmgal_upload.html';
$modversion['templates'][11]['description'] = '';
$modversion['templates'][12]['file'] = 'rmgal_edit_image.html';
$modversion['templates'][12]['description'] = '';

// name of config option for accessing its specified value. i.e. $xoopsModuleConfig['storyhome']
$modversion['config'][1]['name'] = 'comments';

// title of this config option displayed in config settings form
$modversion['config'][1]['title'] = '_MI_RMGAL_COMMENTS';

// description of this config option displayed under title
$modversion['config'][1]['description'] = '_MI_RMGAL_COMMENTSDESC';

// form element type used in config form for this option. can be one of either textbox, textarea, select, select_multi, yesno, group, group_multi
$modversion['config'][1]['formtype'] = 'yesno';

// value type of this config option. can be one of either int, text, float, array, or other
// form type of 'group_multi', 'select_multi' must always be 'array'
// form type of 'yesno', 'group' must be always be 'int'
$modversion['config'][1]['valuetype'] = 'int';

// the default value for this option
// ignore it if no default
// 'yesno' formtype must be either 0(no) or 1(yes)
$modversion['config'][1]['default'] = 1;

// options to be displayed in selection box
// required and valid for 'select' or 'select_multi' formtype option only
// language constants can be used for both array keys and values
$modversion['config'][1]['options'] = array('0' => 'No', '1' => 'Si');

//quien puede enviar comentarios
$modversion['config'][2]['name'] = 'whocomment';
$modversion['config'][2]['title'] = '_MI_RMGAL_WHOCOM';
$modversion['config'][2]['description'] = '_MI_RMGAL_WHOCOMDESC';
$modversion['config'][2]['formtype'] = 'yesno';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = 0;
$modversion['config'][2]['options'] = array('0' => 'No', '1' => 'Si');

//Permitir la creación de nuevas galerías
$modversion['config'][3]['name'] = 'formatdate';
$modversion['config'][3]['title'] = '_MI_RMGAL_FORMATDATE';
$modversion['config'][3]['description'] = '';
$modversion['config'][3]['formtype'] = 'textbox';
$modversion['config'][3]['valuetype'] = 'text';
$modversion['config'][3]['default'] = "d/m/Y";

//Permitir la creación de nuevas galerías
$modversion['config'][4]['name'] = 'galname';
$modversion['config'][4]['title'] = '_MI_RMGAL_GALLERYNAME';
$modversion['config'][4]['description'] = '';
$modversion['config'][4]['formtype'] = 'textbox';
$modversion['config'][4]['valuetype'] = 'text';
$modversion['config'][4]['default'] = "RM+Soft Gallery";

//Permitir la creación de nuevas galerías
$modversion['config'][5]['name'] = 'ecards';
$modversion['config'][5]['title'] = '_MI_RMGAL_ECARDS';
$modversion['config'][5]['description'] = '';
$modversion['config'][5]['formtype'] = 'yesno';
$modversion['config'][5]['valuetype'] = 'int';
$modversion['config'][5]['default'] = 1;
$modversion['config'][5]['options'] = array('0' => 'No', '1' => 'Sí');

//Numero de dias para que la categoría se considere nueva
$modversion['config'][6]['name'] = 'newdays';
$modversion['config'][6]['title'] = '_MI_RMGAL_DAYSNEW';
$modversion['config'][6]['description'] = '';
$modversion['config'][6]['formtype'] = 'textbox';
$modversion['config'][6]['valuetype'] = 'int';
$modversion['config'][6]['default'] = 10;

//Total de imágenes nuevas para mostrar
$modversion['config'][7]['name'] = 'newpics';
$modversion['config'][7]['title'] = '_MI_RMGAL_NEWSPIC';
$modversion['config'][7]['description'] = '';
$modversion['config'][7]['formtype'] = 'textbox';
$modversion['config'][7]['valuetype'] = 'int';
$modversion['config'][7]['default'] = 3;

//Total de imágenes por página
$modversion['config'][8]['name'] = 'items';
$modversion['config'][8]['title'] = '_MI_RMGAL_ITEMS';
$modversion['config'][8]['description'] = '';
$modversion['config'][8]['formtype'] = 'textbox';
$modversion['config'][8]['valuetype'] = 'int';
$modversion['config'][8]['default'] = 9;

//Total de imágenes por página
$modversion['config'][8]['name'] = 'items';
$modversion['config'][8]['title'] = '_MI_RMGAL_ITEMS';
$modversion['config'][8]['description'] = '';
$modversion['config'][8]['formtype'] = 'textbox';
$modversion['config'][8]['valuetype'] = 'int';
$modversion['config'][8]['default'] = 9;

//Quien puede mandar postales
$modversion['config'][9]['name'] = 'postcardwho';
$modversion['config'][9]['title'] = '_MI_RMGAL_POSTCARDSWHO';
$modversion['config'][9]['description'] = '';
$modversion['config'][9]['formtype'] = 'yesno';
$modversion['config'][9]['valuetype'] = 'int';
$modversion['config'][9]['default'] = 0;
$modversion['config'][9]['options'] = array('0' => 'No', '1' => 'Sí');

//Dias que permanecen en la base de datos las postcards
$modversion['config'][10]['name'] = 'postcarddays';
$modversion['config'][10]['title'] = '_MI_RMGAL_POSTCARDDAYS';
$modversion['config'][10]['description'] = '';
$modversion['config'][10]['formtype'] = 'textbox';
$modversion['config'][10]['valuetype'] = 'int';
$modversion['config'][10]['default'] = 15;

//Dias que permanecen en la base de datos las postcards
$modversion['config'][11]['name'] = 'bodymail';
$modversion['config'][11]['title'] = '_MI_RMGAL_BODYMAIL';
$modversion['config'][11]['description'] = '';
$modversion['config'][11]['formtype'] = 'textarea';
$modversion['config'][11]['valuetype'] = 'text';
$modversion['config'][11]['default'] = _MI_RMGAL_TEMPHEAD;

// Anchura de los thubnails
$modversion['config'][12]['name'] = 'thumbw';
$modversion['config'][12]['title'] = '_MI_RMGAL_THUMBW';
$modversion['config'][12]['description'] = '';
$modversion['config'][12]['formtype'] = 'textbox';
$modversion['config'][12]['valuetype'] = 'int';
$modversion['config'][12]['default'] = 80;

// Anchura de los thubnails
$modversion['config'][13]['name'] = 'bigw';
$modversion['config'][13]['title'] = '_MI_RMGAL_BIGW';
$modversion['config'][13]['description'] = '';
$modversion['config'][13]['formtype'] = 'textbox';
$modversion['config'][13]['valuetype'] = 'int';
$modversion['config'][13]['default'] = 400;
?>
